// Generated by CoffeeScript 1.7.1
(function() {
  if (Object.prototype.uber == null) {
    Object.defineProperty(Object.prototype, 'uber', {
      enumerable: false,
      value: function(obj, ns) {
        var key, nskey;
        if (obj != null) {
          for (key in obj) {
            if (obj.hasOwnProperty(key)) {
              if (!this.hasOwnProperty(key)) {
                this[key] = obj[key];
              } else if (ns != null) {
                nskey = ns + '_' + key;
                if (this.hasOwnProperty(nskey) || obj.hasOwnProperty(nskey)) {
                  throw new Error('Namespace conflict');
                }
                this[nskey] = obj[key];
              }
            }
          }
        }
        return this;
      }
    });
  } else {
    console.warn("Object.prototype.uber already defined");
  }

}).call(this);
