// Generated by CoffeeScript 1.6.3
(function() {
  Object.defineProperty(Object.prototype, 'uber', {
    enumerable: false,
    value: function(obj, ns) {
      var key, nskey;
      if (obj != null) {
        for (key in obj) {
          if (obj.hasOwnProperty(key)) {
            if (!this.hasOwnProperty(key)) {
              this[key] = obj[key];
            } else if (ns != null) {
              nskey = ns + '_' + key;
              if (this.hasOwnProperty(nskey) || obj.hasOwnProperty(nskey)) {
                throw new Error('Namespace conflict');
              }
              this[nskey] = obj[key];
            }
          }
        }
      }
      return this;
    }
  });

}).call(this);
